version: "3.8"
services:
  postgres:
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./pgdata:/var/lib/postgressql/data
